spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stock_control
    username: root
    password: Yagami40811091
    jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false