spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/grupo-17-bdd-oo2-2020?serverTimezone=UTC
    username: root
    password: F666thepolice
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false